GET_FILENAME_COMPONENT(TOOL_NAME "${CMAKE_CURRENT_SOURCE_DIR}" NAME)
STRING(PREPEND TOOL_NAME "${PROJECT_NAME}-")
FILE(GLOB_RECURSE TOOL_FILES CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/*.cpp" "${CMAKE_CURRENT_SOURCE_DIR}/*.hpp")
ADD_EXECUTABLE(${TOOL_NAME} ${TOOL_FILES})
TARGET_INCLUDE_DIRECTORIES(${TOOL_NAME} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/")
TARGET_LINK_LIBRARIES(${TOOL_NAME} PRIVATE zeroslam-common)
TARGET_LINK_LIBRARIES(${TOOL_NAME} PRIVATE Threads::Threads)
SET_TARGET_PROPERTIES(${TOOL_NAME} PROPERTIES FOLDER tools)